package org.prezydium.streets.repository;

import java.util.Arrays;
import java.util.List;

public class StreetsRepository {

    private String[] streets = {
            "﻿MACIEJA",
            "MACIEJA KAMIEŃSKIEGO",
            "MACIEJKOWA",
            "MACIERZANKOWA",
            "MAGELLANA",
            "MAGNOLIOWA",
            "MAJEWSKICH",
            "MAJOWA",
            "MAKI",
            "MAKSYMILIANA GIERYMSKIEGO",
            "MALBORSKA",
            "MALINOWA",
            "MAŁOMIEJSKA",
            "MAŁOOGRODOWA",
            "MANIFESTU POŁANIECKIEGO",
            "MARCINA DRAGANA",
            "MARCOWA",
            "MARIACKA",
            "MARIANA BUCZKA",
            "MARIANA HEMARA",
            "MARIANA KOŁODZIEJA",
            "MARIANA PELCZARA",
            "MARIANA SEREDYŃSKIEGO",
            "MARIANA SMOLUCHOWSKIEGO",
            "MARII KONOPNICKIEJ",
            "MARII KURECKIEJ",
            "MARII LUDWIKI",
            "MARII SKŁODOWSKIEJ-CURIE",
            "MARIUSZA ZARUSKIEGO",
            "MARSA",
            "MARSZ. FERDYNANDA FOCHA",
            "MARYLI",
            "MARYNARKI POLSKIEJ",
            "MARYNARSKA",
            "MARZEŃ",
            "MASZYNOWA",
            "MATECZNIKOWA",
            "MATEMBLEWSKA",
            "MATKI POLKI",
            "MAURYCEGO BENIOWSKIEGO",
            "MAZOWIECKA",
            "MAZURSKA",
            "MERKUREGO",
            "METALOWCÓW",
            "METEORYTOWA",
            "MEZOWSKA",
            "MIAŁKI SZLAK",
            "MICHAŁA DRZYMAŁY",
            "MICHAŁA GLINKI",
            "MICHAŁA OGIŃSKIEGO",
            "MIECHUCIŃSKA",
            "MIECZYSŁAWA BOGUCKIEGO",
            "MIECZYSŁAWA KARŁOWICZA",
            "MIECZYSŁAWA NIEDZIAŁKOWSKIEGO",
            "MIECZYSŁAWY ĆWIKLIŃSKIEJ",
            "MIEDZA",
            "MIEDZIANA",
            "MIESZCZAŃSKA",
            "MIESZKA I",
            "MIĘDZYGWIEZDNA",
            "MIGOWSKA",
            "MIKOŁAJA DZIAŁYŃSKIEGO",
            "MIKOŁAJA GOMÓŁKI",
            "MIKOŁAJA KOPERNIKA",
            "MIKOŁAJA REJA",
            "MIŁA",
            "MIŁOCIŃSKA",
            "MIŁOSNA",
            "MINERWY",
            "MINOGI",
            "MIODOWA",
            "MIRACHOWSKA",
            "MIRANDY",
            "MISZEWSKIEGO",
            "MJR. HENRYKA SUCHARSKIEGO",
            "MJR. HUBALA",
            "MJR. MIECZYSŁAWA SŁABEGO",
            "MŁODZIEŻY POLSKIEJ",
            "MŁYŃSKA",
            "MNISZKI",
            "MODRA",
            "MONTAŻYSTÓW",
            "MORELOWA",
            "MORENOWA",
            "MORENOWE WZGÓRZE",
            "MORSKA",
            "MOSTEK",
            "MOSTOWA",
            "MOTŁAWSKA",
            "MŚCIWOJA II",
            "MYLNA",
            "MYŚLIBORSKA",
            "MYŚLIWSKA",
            "MYŚLIWSKIE WZGÓRZE",
            "FRYDERYKA CHOPINA",
            "FRANCISZKA SCHUBERTA",
            "FRANCISZKA LISZTA",
            "BZOWA",
            "BUKOWA",
            "BULOŃSKA",
            "BURGASKA",
            "BURSZTYNOWA",
            "ALEKSANDRA VOLTY",
            "ALEKSANDRA ZELWEROWICZA",
            "ANDROMEDY",
            "ARKOŃSKA",
            "ARTEMIDY",
            "ELEWÓW",
            "ELFÓW",
            "BIAŁA",
            "ARTURA SCHOPENHAUERA",
            "ASESORA",
            "FABRYCZNA",
            "DALEKA",
            "DALIOWA",
            "DAMAZEGO TILGNERA",
            "DAMROKI",
            "DANIELA CHODOWIECKIEGO",
            "DANIELA FAHRENHEITA",
            "DANUSI",
            "DARŁOWSKA",
            "DARU POMORZA",
            "DARŻLUBSKA",
            "DĄBROWSZCZAKÓW",
            "DĄBRÓWKI",
            "DEDALA",
            "DELFINA",
            "DEOTYMY",
            "DĘBINKI",
            "DĘBOWA",
            "DIAMENTOWA",
            "DIANY",
            "DIONIZOSA",
            "DŁUGA",
            "DŁUGA GROBLA",
            "DŁUGI TARG",
            "DŁUGIE OGRODY",
            "DŁUGIE POBRZEŻE",
            "DO STUDZIENKI",
            "DOBRA",
            "DOBRZYŃSKICH",
            "DOJAZDOWA",
            "DOKERÓW",
            "DOKI",
            "DOLNA",
            "DOLNA BRAMA",
            "DOLNE MIGOWO",
            "DOLNE MŁYNY",
            "DR. WŁADYSŁAWA PANECKIEGO",
            "DRAWSKA",
            "DROŻYNY",
            "DRUŻYN STRZELECKICH",
            "DRWĘCKA",
            "DULKOWA",
            "DWORCOWA",
            "DWORKOWA",
            "DWORSKA",
            "DYREKCYJNA",
            "DYWIZJI WOŁYŃSKIEJ",
            "DYWIZJONU 303",
            "DZIANA",
            "DZIELNA",
            "DZWONKI",
            "DŹWIGOWA",
            "NA PIASKACH",
            "NA STĘPCE",
            "NA STOKU",
            "NA SZAŃCACH",
            "NA WZGÓRZU",
            "NA ZASPĘ",
            "NA ZBOCZU",
            "NAD BRZEGIEM",
            "NAD JAREM",
            "NAD POTOKIEM",
            "NAD STARĄ RADUNIĄ",
            "NAD STAWEM",
            "NADMORSKA",
            "NADMORSKI DWÓR",
            "NADWIŚLAŃSKA",
            "NADWODNA",
            "NAGIETKOWA",
            "NARCIARSKA",
            "NARCYZOWA",
            "NAREWSKA",
            "NARWICKA",
            "NAWIGATORÓW",
            "NEPTUNA",
            "NICCOLA PAGANINIEGO",
            "NICCOLO PAGANINIEGO",
            "NIDZICKA",
            "NIEBOROWSKA",
            "NIECAŁA",
            "NIEDZIAŁKOWSKIEGO",
            "NIEDŹWIEDNIK",
            "NIEGOCIŃSKA",
            "NIEGOWO",
            "NIEGOWSKA",
            "NIEPOŁOMICKA",
            "NIEZAPOMINAJEK",
            "NIKE",
            "NISKA",
            "NIWKI",
            "NOTECKA",
            "NOWA",
            "NOWATORÓW",
            "NOWE OGRODY",
            "NOWIEC",
            "NOWINY",
            "NOWOGRÓDZKA",
            "NOWOLIPIE",
            "NOWOSĄDECKA",
            "NOWOTNA",
            "NOWY ŚWIAT",
            "ŹRÓDLANA",
            "ŻABI KRUK",
            "ŻABIA",
            "ŻAGLOWA",
            "ŻAKÓW",
            "ŻARNOWIECKA",
            "ŻEGLARSKA",
            "ŻNIWNA",
            "ŻOŁNIERSKA",
            "ŻONKILOWA",
            "ŻUBROWA",
            "ŻUKOWSKA",
            "ŻUŁAWSKA",
            "ŻURAWIA",
            "ŻWIRKI I WIGURY",
            "ŻYCZLIWA",
            "ŻYWIECKA",
            "ALEJA GRUNWALDZKA",
            "BELGRADZKA",
            "ŁAPALICKA",
            "BERENIKI",
            "BERNARDA CHRZANOWSKIEGO",
            "BESKIDZKA",
            "PACHOŁÓW",
            "PAGÓRKOWA",
            "PANA TADEUSZA",
            "PANIEŃSKA",
            "PAŃSKA",
            "PARKINGOWA",
            "PARKOWA",
            "PARTEROWA",
            "PARTYZANTÓW",
            "PARYSA",
            "PASIECZNA",
            "PAWIA",
            "PAWŁA GDAŃCA",
            "PEGAZA",
            "PELPLIŃSKA",
            "PENELOPY",
            "PERŁOWA",
            "PERSEUSZA",
            "PIASKOWA",
            "PIASTOWSKA",
            "PIECEWSKA",
            "PIEKARNICZA",
            "PIENIŃSKA",
            "PIESZA",
            "PILOTÓW",
            "PIŁKARSKA",
            "PIOTRA CZAJKOWSKIEGO",
            "PIOTRA MICHAŁOWSKIEGO",
            "PIOTRA NORBLINA",
            "PIOTRKOWSKA",
            "PIWNA",
            "PLAC BRONISŁAWA KOMOROWSKIEGO",
            "PLAC DWORCOWY",
            "PLAC GEN. JÓZEFA WYBICKIEGO",
            "PLAC KS. GUSTKOWICZA",
            "PLAC KS. PRŁ. JANA GUSTKOWICZA",
            "PLAC OBROŃCÓW POCZTY POLSKIEJ",
            "PLAC ORUŃSKI",
            "PLAC WAŁOWY",
            "PLANETARNA",
            "PLATYNOWA",
            "PLEJADY",
            "PŁK. JANA PAŁUBICKIEGO",
            "PŁK. WILKA-KRZYŻANOWSKIEGO",
            "PŁOCKA",
            "PŁOŃSKA",
            "PŁOWCE",
            "PO SCHODKACH",
            "POBIEDZISKO",
            "POCZTY GDAŃSKIEJ",
            "POD ZRĘBEM",
            "PODBIELAŃSKA",
            "PODCHORĄŻYCH",
            "PODGARBARY",
            "PODHALAŃSKA",
            "PODJAZD",
            "PODKARPACKA",
            "PODKOMORZEGO",
            "PODLEŚNA",
            "PODMIEJSKA",
            "PODMŁYŃSKA",
            "PODMURZE",
            "PODWALE GRODZKIE",
            "PODWALE PRZEDMIEJSKIE",
            "PODWALE STAROMIEJSKIE",
            "PODZAMCZE",
            "POGODNA",
            "POHULANKA",
            "POLANKI",
            "POLESKA",
            "POLI GOJAWICZYŃSKIEJ",
            "POLITECHNICZNA",
            "POLNA",
            "POLONII GDAŃSKIEJ",
            "POLSKIEGO CZERWONEGO KRZYŻA",
            "POŁĘŻE",
            "POŁUDNIOWA",
            "POMORSKA",
            "POŃCZOSZNIKÓW",
            "POPRZECZNA",
            "PORĘBSKIEGO",
            "PORTOWCÓW",
            "PORZECZKOWA",
            "POSEJDONA",
            "POTĘGOWSKA",
            "SKM PRZYMORZE",
            "BOHATERÓW GETTA WARSZAWSKIEGO",
            "BOLESŁAWA PRUSA",
            "BORCHARDTA",
            "BORÓWKOWA",
            "BORSKA",
            "BORSUCZA",
            "BOTANICZNA",
            "BPA ANDRZEJA WRONKI",
            "BPA. HIERONIMA ROZRAŻEWSKIEGO",
            "BPA. KONSTANTYNA DOMINIKA",
            "BRACKA",
            "BRATKI",
            "BRODNICKA",
            "BRONIEWSKIEGO",
            "BRONISŁAWA BUKOWSKIEGO",
            "BRONISŁAWA CZECHA",
            "BROWARNA",
            "BRUKOWA",
            "BRYGIDKI",
            "BRYLANTOWA",
            "BRZEGI",
            "BRZEŹNIEŃSKA",
            "BRZOSKWINIOWA",
            "ANTONIEGO LENDZIONA",
            "ANTONIEGO ABRAHAMA",
            "ANGIELSKA GROBLA",
            "ALEJA ZWYCIĘSTWA",
            "ANDRZEJA HUENEFELDA",
            "ANDRZEJA MODRZEWSKIEGO",
            "ŁĘCZYCKA",
            "ŁĘGI",
            "ŁOSIA",
            "ŁOSTOWICKA",
            "ŁOWCÓW",
            "ŁOWICKA",
            "BURSZTYNOWA",
            "BYTOWSKA",
            "BUKOWA",
            "EUGENIUSZA ROMERA",
            "FENIKSA",
            "JABŁONIOWA",
            "JACHTOWA",
            "JACKA MALCZEWSKIEGO",
            "JACKA SOPLICY",
            "JAGATOWSKA",
            "JAKUBA WEJHERA",
            "JAŁMUŻNICZA",
            "JANA BAŻYŃSKIEGO",
            "JANA BROŻKA",
            "JANA BRZECHWY",
            "JANA CHRYZOSTOMA PASKA",
            "JANA CZIRENBERGA",
            "JANA DANTYSZKA",
            "JANA DEKERTA",
            "JANA DŁUGOSZA",
            "JANA DZIEWANOWSKIEGO",
            "JANA HEWELIUSZA",
            "JANA HUSA",
            "JANA KARSKIEGO",
            "JANA KASPROWICZA",
            "JANA KEPLERA",
            "JANA KIELASA",
            "JANA KILIŃSKIEGO",
            "JANA KOCHANOWSKIEGO",
            "JANA KOZIETULSKIEGO",
            "JANA MATEJKI",
            "JANA NAGÓRSKIEGO",
            "JANA OSTROROGA",
            "JANA PESTALOZZIEGO",
            "JANA RYBIŃSKIEGO",
            "JANA SEBASTIANA BACHA",
            "JANA SOBIESKIEGO",
            "JANA SOLIKOWSKIEGO",
            "JANA STRAKOWSKIEGO",
            "JANA UPHAGENA",
            "JANA WOJNARSKIEGO",
            "JANA Z KOLNA",
            "JANKIELA",
            "JANTAROWA",
            "JANUSZA KORCZAKA",
            "JANUSZA KUSOCIŃSKIEGO",
            "JANUSZA MEISSNERA",
            "JAROSZA HENRYKA DERDOWSKIEGO",
            "JAROWA",
            "JARZĘBINOWA",
            "JASIA I MAŁGOSI",
            "JASIEŃSKA",
            "JASKÓŁCZA",
            "JASNA",
            "JASTRZĘBIA",
            "JAŚKOWA DOLINA",
            "JAŚMINOWA",
            "JAŚMINOWY STOK",
            "JAWOROWA",
            "JAWORZNIAKÓW",
            "JEDNOROŻCA",
            "JELENIA",
            "JELENIOGÓRSKA",
            "JELINKI",
            "JELITKOWSKA",
            "JELITKOWSKI DWÓR",
            "JEREMIASZA FALCK POLONUSA",
            "JERZEGO BAJANA",
            "JERZEGO GIEDROYCIA",
            "JERZEGO ŚWIRSKIEGO",
            "JERZEGO WALDORFFA",
            "JERZEGO ZWIERKOWSKIEGO",
            "JESIENNA",
            "JESIONOWA",
            "JEZIOROWA",
            "JOACHIMA LELEWELA",
            "JOACHIMA PASTORIUSZA",
            "JODŁOWA",
            "JODOWA",
            "JOWISZA",
            "JÓZEFA CHEŁMOŃSKIEGO",
            "JÓZEFA CHOCISZEWSKIEGO",
            "JÓZEFA CZYŻEWSKIEGO",
            "JÓZEFA HOENE-WROŃSKIEGO",
            "JÓZEFA KOTARBIŃSKIEGO",
            "JÓZEFA KRASZEWSKIEGO",
            "JÓZEFA MEHOFFERA",
            "JÓZEFA PANKIEWICZA",
            "JÓZEFA UNRUGA",
            "JÓZEFA WASSOWSKIEGO",
            "JÓZEFA WIENIAWSKIEGO",
            "JÓZEFA ŻYLEWICZA",
            "JULIANA NIEMCEWICZA",
            "JULIANA TUWIMA",
            "JULIUSZA KOSSAKA",
            "JULIUSZA OSTERWY",
            "JULIUSZA SŁOWACKIEGO",
            "JUNACKA",
            "JUNONY",
            "JURATY",
            "JUTRZENKI",
            "ŁÓDZKA",
            "ŁUCZNICZA",
            "ŁUŻYCKA",
            "ŁYŻWIARSKA",
            "I BRYGADY",
            "II BRYGADY",
            "ALFA LICZMAŃSKIEGO",
            "ALFREDA NOBLA",
            "ALINY PIENKOWSKIEJ",
            "ALOJZEGO BRUSKIEGO",
            "ALTANKI",
            "AMETYSTOWA",
            "ALEKSANDRA PUSZKINA",
            "ALEKSANDRA RYLKEGO",
            "FRANCISZKA ZABŁOCKIEGO",
            "FRANCISZKA ZUBRZYCKIEGO",
            "FREZJOWA",
            "FROMBORSKA",
            "ŁAŃCUCKA",
            "ASTRONOMÓW",
            "OBOTRYCKA",
            "OBROŃCÓW WESTERPLATTE",
            "OBYWATELSKA",
            "ODRZAŃSKA",
            "OFIAR GRUDNIA 70",
            "OFIAR GRUDNIA'70",
            "OGARNA",
            "OGRODOWA",
            "OJCOWSKA",
            "OKOPOWA",
            "OKÓLNA",
            "OKRĄG",
            "OKRĘTOWA",
            "OKSYWSKA",
            "OLCHOWA",
            "OLEJARNA",
            "OLIMPIJSKA",
            "OLIWKOWA",
            "OLIWSKA",
            "OLSZTYŃSKA",
            "OLSZYŃSKA",
            "OŁOWIANKA",
            "OPACKA",
            "OPATA JACKA RYBIŃSKIEGO",
            "OPŁOTKI",
            "OPOLSKA",
            "ORAŃSKA",
            "ORFEUSZA",
            "ORIONA",
            "ORKANA",
            "ORLA",
            "ORLĄT LWOWSKICH",
            "ORŁOWSKA",
            "ORNITOLOGÓW",
            "ORZECHOWA",
            "OSIEDLE",
            "OSIEDLOWA",
            "OSIEK",
            "OSKARA KOLBERGA",
            "OSOWSKI ZAKĄTEK",
            "OSTROŁĘCKA",
            "OSTRZYCKA",
            "OTAGO",
            "OTOMIŃSKA",
            "OTWARTA",
            "OWCZARNIA",
            "OZYRYSA",
            "U FURTY",
            "UBOCZE",
            "UCZNIOWSKA",
            "UGORY",
            "UJEŚCISKO",
            "UKOŚNA",
            "UKRYTA",
            "UŁAŃSKA",
            "URANA",
            "URANOWA",
            "UROCZA",
            "URWISTA",
            "USTRONIE",
            "UZDROWISKOWA",
            "VICTORII",
            "VII DWÓR",
            "ZA MURAMI",
            "ZABYTKOWA",
            "ZACISZE",
            "ZACNA",
            "ZAGONY",
            "ZAGÓRNA",
            "ZAGROBLE",
            "ZAGRODOWA",
            "ZAJĘCZA",
            "ZAKOLE",
            "ZAKONICZYŃSKA",
            "ZAKOPIAŃSKA",
            "ZAKOSY",
            "ZALESIE",
            "ZAŁOGOWA",
            "ZAMIEJSKA",
            "ZAMKNIĘTA",
            "ZAMKOWA",
            "ZAMOJSKA",
            "ZAROŚLAK",
            "ZAŚCIANEK",
            "ZATOKOWA",
            "ZAUŁEK ŚW. BARTŁOMIEJA",
            "ZAWIEJSKA",
            "ZAWILCOWA",
            "ZAWISZY CZARNEGO",
            "ZAWIŚLAŃSKA",
            "ZAWODNIKÓW",
            "ZAWODZIE",
            "ZBĄSZYŃSKA",
            "ZBIEŻNA",
            "ZBIGNIEWA BURZYŃSKIEGO",
            "ZBIGNIEWA CYBULSKIEGO",
            "ZBIGNIEWA PODLECKIEGO",
            "ZBYSZKA Z BOGDAŃCA",
            "ZBYTKI",
            "ZDROJOWA",
            "ZENITOWA",
            "ZEUSA",
            "ZGODY I",
            "ZGODY II",
            "ZIELNA",
            "ZIELONA",
            "ZIELONE WZGÓRZE",
            "ZIELONOGÓRSKA",
            "ZIELONY STOK",
            "ZIELONY TRÓJKĄT",
            "ZIELONY ZAKĄTEK",
            "ZIEMOWITA",
            "ZIMNA",
            "ZŁOTA",
            "ZŁOTA KARCZMA",
            "ZŁOTNIKÓW",
            "ZŁOTOWSKA",
            "ZOFII NAŁKOWSKIEJ",
            "ZOSI",
            "ZUCHÓW",
            "ZWIĄZKOWA",
            "ZWIĄZKU JASZCZURCZEGO",
            "ZWIERZYNIECKA",
            "ZYGMUNTA AUGUSTA",
            "ZYGMUNTA NOSKOWSKIEGO",
            "ZYGMUNTA RUMLA",
            "ZYGMUNTA WRÓBLEWSKIEGO",
            "OBROŃCÓW WYBRZEŻA",
            "BOLESŁAWA CHROBREGO",
            "BOGUMIŁA KOBIELI",
            "ANDRZEJA GRUBBY",
            "ALEKSANDRA FREDRY",
            "FELIKSA NOWOWIEJSKIEGO",
            "ALEKSANDRA GRYGLEWSKIEGO",
            "ANDRZEJA STRUGA",
            "ELIZY ORZESZKOWEJ",
            "ALEKSANDRA MAJKOWSKIEGO",
            "GABRIELA RZĄCZYŃSKIEGO",
            "GAJOWA",
            "GALAKTYCZNA",
            "GALILEUSZA",
            "GARBARY",
            "GARNCARSKA",
            "GAZOWNICZA",
            "GDAŃSKA",
            "GDAŃSK-BRZEŹNO",
            "GDAŃSKIEGO KOLEJARZA",
            "GDYŃSKA",
            "GDYŃSKICH KOSYNIERÓW",
            "GEN. ANTONIEGO GIEŁGUDA",
            "GEN. AUGUSTA EMILA FIELDORFA",
            "GEN. BORA-KOMOROWSKIEGO",
            "GEN. DE GAULLE'A",
            "GEN. ELŻBIETY ZAWACKIEJ",
            "GEN. HENRYKA DĄBROWSKIEGO",
            "GEN. JÓZEFA BEMA",
            "GEN. JÓZEFA FISZERA",
            "GEN. JÓZEFA SOWIŃSKIEGO",
            "GEN. KAZIMIERZA SOSNKOWSKIEGO",
            "GEN. LEOPOLDA OKULICKIEGO",
            "GEN. STEFANA GROTA-ROWECKIEGO",
            "GEODETÓW",
            "GERWAZEGO",
            "GĘSIA",
            "GŁĘBOKA",
            "GŁOGOWA",
            "GŁOGOWSKA",
            "GŁUCHA",
            "GŁUSZCA",
            "GNIEŹNIEŃSKA",
            "GNILNA",
            "GOŁĘBIA",
            "GOŁUŃSKA",
            "GOPLAŃSKA",
            "GORZOWSKA",
            "GOSKA",
            "GOSPODY",
            "GOSTYŃSKA",
            "GOSZYŃSKA",
            "GOŚCINNA",
            "GOTYCKA",
            "GÓRALSKA",
            "GÓRECKA",
            "GÓRKA",
            "GÓRNICZA",
            "GÓRZYSTA",
            "GRABOWA",
            "GRADOWA",
            "GRANITOWA",
            "GRAŻYNY",
            "GRAŻYNY BACEWICZ",
            "GROBLA I",
            "GROBLA II",
            "GROBLA III",
            "GROBLA IV",
            "GRODZA KAMIENNA",
            "GRODZIEŃSKA",
            "GRODZKA",
            "GRONOSTAJOWA",
            "GROSZKOWA",
            "GRUDZIĄDZKA",
            "GRYFA POMORSKIEGO",
            "GRZEGORZA FITELBERGA",
            "GRZEGORZA PIRAMOWICZA",
            "GRZEGORZA Z SANOKA",
            "GRZYBOWA",
            "GUSTAWA HERLINGA-GRUDZIŃSKIEGO",
            "GWIAZDA MORZA",
            "GWIAŹDZISTA",
            "HANDLOWA",
            "HARFOWA",
            "HELENY",
            "HELENY MARUSARZÓWNY",
            "HELENY MODRZEJEWSKIEJ",
            "HELIOSA",
            "HELSKA",
            "HENRYKA ARCTOWSKIEGO",
            "HENRYKA HUBERTUSA JABŁOŃSKIEGO",
            "HENRYKA RODAKOWSKIEGO",
            "HENRYKA SIEMIRADZKIEGO",
            "HENRYKA SIENKIEWICZA",
            "HENRYKA WIECZORKIEWICZA",
            "HERBOWA",
            "HERKULESA",
            "HERMESA",
            "HEROSA",
            "HERY",
            "HESTII",
            "HIACYNTOWA",
            "HOKEJOWA",
            "HOŁDU PRUSKIEGO",
            "HOMERA",
            "HORACEGO",
            "HORESZKÓW",
            "HOŻA",
            "HUGO KOŁŁĄTAJA",
            "HUSYTÓW",
            "IGIELNICKA",
            "IGNACEGO DOMEYKI",
            "IGNACEGO KRASICKIEGO",
            "IGNACEGO KURZYŃSKIEGO",
            "IGNACEGO PADEREWSKIEGO",
            "IKARA",
            "IŁAWSKA",
            "IŁOWA",
            "INSPEKTORSKA",
            "INSTALATORÓW",
            "INTERNETOWA",
            "INŻYNIERSKA",
            "IRYSOWA",
            "IWO GALLA",
            "IZYDY",
            "JAGIELLOŃSKA",
            "BIOLOGICZNA",
            "AMUNDSENA",
            "ANTYGONY",
            "ARENDA DICKMANA",
            "FLORIANA CEYNOWY",
            "FLORY",
            "FORSYCJI",
            "FRANCISZKA BOHOMOLCA",
            "EMILII PLATER",
            "BUDAPESZTAŃSKA",
            "ARTURA GROTTGERA",
            "BYDGOSKA",
            "BRZOZOWA",
            "FIGOWA",
            "ALEJA WOJSKA POLSKIEGO",
            "POTOKOWA",
            "POWALNA",
            "POWROŹNICZA",
            "POWSTANIA KOŚCIUSZKOWSKIEGO",
            "POWSTANIA LISTOPADOWEGO",
            "POWSTANIA STYCZNIOWEGO",
            "POWSTAŃCÓW WARSZAWSKICH",
            "POWSTAŃCÓW WIELKOPOLSKICH",
            "POZIOMKOWA",
            "POZNAŃSKA",
            "PÓLNICY",
            "PÓŁNOCNA",
            "PROF. JÓZEFA WIĘCKOWSKIEGO",
            "PROF. KAZIMIERZA KOPECKIEGO",
            "PROF. MARIANA RACIBORSKIEGO",
            "PROF. MICHAŁA SIEDLECKIEGO",
            "PROF. ROMANA LIPOWICZA",
            "PROF. ROMUALDA CEBERTOWICZA",
            "PROF. STANISŁAWA SZPORA",
            "PROF. STEFANA HAUSBRANDTA",
            "PROF. STEFANA MYCZKOWSKIEGO",
            "PROF. ZYGMUNTA CZUBIŃSKIEGO",
            "PROF.STANISŁAWA SZPORA",
            "PROMETEUSZA",
            "PROMIENISTA",
            "PROTAZEGO",
            "PRÓŻNA",
            "PRZEBIŚNIEGOWA",
            "PRZEGALIŃSKA",
            "PRZEŁOM",
            "PRZEMIAN",
            "PRZEMYSKA",
            "PRZEMYSŁOWA",
            "PRZESMYK",
            "PRZETOCZNA",
            "PRZĘDZALNICZA",
            "PRZY TORZE",
            "PRZYBRZEŻNA",
            "PRZYJEMNA",
            "PRZYOKOPOWA",
            "PRZYRODNIKÓW",
            "PRZYTULNA",
            "PTASIA",
            "PUCKA",
            "PUSTA",
            "TABOROWA",
            "TADEUSZA GWIAZDOWSKIEGO",
            "TADEUSZA JASIŃSKIEGO",
            "TADEUSZA KOŚCIUSZKI",
            "TADEUSZA REJTANA",
            "TADEUSZA SYGIETYŃSKIEGO",
            "TADEUSZA TYLEWSKIEGO",
            "TADEUSZA WENDY",
            "TAMA PĘDZICHOWSKA",
            "TAMKA",
            "TANDETA",
            "TANECZNA",
            "TARASY",
            "TARCICE",
            "TARG DRZEWNY",
            "TARG RYBNY",
            "TARNINY",
            "TARNOWSKA",
            "TARTACZNA",
            "TATRZAŃSKA",
            "TELESKOPOWA",
            "TELEWIZYJNA",
            "TELIMENY",
            "TEMIDY",
            "TENISOWA",
            "TEOFILA LENARTOWICZA",
            "TEZEUSZA",
            "TĘCZOWA",
            "TKACKA",
            "TOBIASZA",
            "TOLKMICKA",
            "TOMASZA EDISONA",
            "TOPAZOWA",
            "TOPOLOWA",
            "TORUŃSKA",
            "TRAKT ŚW. WOJCIECHA",
            "TRAŁOWA",
            "TRANSPORTOWCÓW",
            "TRAPOWA",
            "TRAWKI",
            "TRUBADURÓW",
            "TRZY LIPY",
            "TUCHOMSKA",
            "TULIPANÓW",
            "TURKUSOWA",
            "TURYSTYCZNA",
            "TURZYCOWA",
            "TWARDA",
            "TYMIANKOWA",
            "TYSIĄCLECIA",
            "TYTUSA CHAŁUBIŃSKIEGO",
            "BAŻANTOWA",
            "BUDOWLANYCH",
            "BYSEWSKA",
            "BYSTRZYCKA",
            "EDMUNDA BIERNACKIEGO",
            "EDWARDA STACHURY",
            "EGIERTOWSKA",
            "ELBLĄSKA",
            "EMILII HOENE",
            "EUGENIUSZA KWIATKOWSKIEGO",
            "EURYDYKI",
            "FALISTA",
            "FALOWA",
            "FELIKSA MUZYKA",
            "ALEJA LEGIONÓW",
            "ALEKSANDRA DULIN'A",
            "FILARETÓW",
            "FILOMATÓW",
            "FLISACKA",
            "FRANCISZKA BELLINGA",
            "FRANCISZKA HYNKA",
            "FRANCISZKA KRĘCKIEGO",
            "FRANCISZKA KUBACZA",
            "FUNDACYJNA",
            "ŁAGIEWNIKI",
            "ŁANOWA",
            "ŁĄKOWA",
            "ŁABĘDZIA",
            "KONRADA KORZENIOWSKIEGO",
            "KONRADA LECZKOWA",
            "KONRADA WALLENRODA",
            "KONSTANTEGO BERGIELA",
            "KONSTANTEGO CIOŁKOWSKIEGO",
            "KONSTANTEGO IL. GAŁCZYŃSKIEGO",
            "KONSTANTEGO ILDEFONSA GAŁCZYŃSKIEGO",
            "KONSTELACJI",
            "KONWALII",
            "KOPALNIANA",
            "KORALOWA",
            "KORMORANÓW",
            "KORNELA MAKUSZYŃSKIEGO",
            "KORSARZY",
            "KORTOWSKA",
            "KORZENNA",
            "KOSMONAUTÓW",
            "KOSZALIŃSKA",
            "KOŚCIERSKA",
            "KOTWICZNIKÓW",
            "KOWALSKA",
            "KOZIA",
            "KOZIOROŻCA",
            "KPT. KAROLA OLGIERDA BORCHARDTA",
            "KPT. KONSTANTEGO MACIEJEWICZA",
            "KRAJEŃSKA",
            "KRAŃCOWA",
            "KRASNOLUDKÓW",
            "KRAŚNIĘTA",
            "KRĘTA",
            "KROKUSOWA",
            "KROSNA",
            "KROWODERSKA",
            "KRÓLEWSKIE WZGÓRZE",
            "KRÓLIKARNIA",
            "KRÓLOWEJ BONY",
            "KRÓLOWEJ JADWIGI",
            "KRÓTKA",
            "KRUCZA",
            "KRUSZWICKA",
            "KRYLOWA",
            "KRYNICKA",
            "KRYNICZNA",
            "KRYSZTAŁOWA",
            "KRZEMOWA",
            "KRZYSZTOFA ARCISZEWSKIEGO",
            "KRZYSZTOFA KAMILA BACZYŃSKIEGO",
            "KRZYSZTOFA KOLUMBA",
            "KRZYSZTOFA MRONGOWIUSZA",
            "KRZYWA",
            "KS. BERNARDA SYCHTY",
            "KS. FRANCISZKA ROGACZEWSKIEGO",
            "KS. JANA MAJDERA",
            "KS. JÓZEFA TISCHNERA",
            "KS. JÓZEFA ZATOR PRZYTOCKIEGO",
            "KS. LEONA MISZEWSKIEGO",
            "KS. MARIANA GÓRECKIEGO",
            "KSAWEREGO DUNIKOWSKIEGO",
            "KSIĘCIA JÓZEFA PONIATOWSKIEGO",
            "KSIĘDZA ROBAKA",
            "KU UJŚCIU",
            "KUBUSIA PUCHATKA",
            "KUPAŁY",
            "KURIERÓW AK",
            "KURIERÓW ARMII KRAJOWEJ",
            "KURKOWA",
            "KURZA",
            "KUSZNIKÓW",
            "KUTNOWSKA",
            "KWIATOWA",
            "KWIDZYŃSKA",
            "KWIETNA",
            "KWIETNIOWA",
            "LASTADIA",
            "LATARNIANA",
            "LAWENDOWA",
            "LAWENDOWE WZGÓRZE",
            "LAZUROWA",
            "LECHA",
            "LECHA BĄDKOWSKIEGO",
            "LEDY",
            "LEGENDY",
            "LEGNICKA",
            "LEKTYKARSKA",
            "LEONA DROSZYŃSKIEGO",
            "LEONA KRUCZKOWSKIEGO",
            "LEONA WYCZÓŁKOWSKIEGO",
            "LEONIDA TELIGI",
            "LESZCZYNOWA",
            "LESZCZYŃSKICH",
            "LESZKA BIAŁEGO",
            "LEŚNA",
            "LEŚNA GÓRA",
            "LEŚNY POTOK",
            "LEŚNY STOK",
            "LETNIA",
            "LETNICKA",
            "LETNISKOWA",
            "LEWKONIOWA",
            "LEŹNIEŃSKA",
            "LĘBORSKA",
            "LILIOWA",
            "LILLI WENEDY",
            "LIMBOWA",
            "LIPCE",
            "LIPCOWA",
            "LIPOWA",
            "LIPUSKA",
            "LIROWA",
            "LISIA GROBLA",
            "LISTKI",
            "LITEWSKA",
            "LOTNIKÓW POLSKICH",
            "LUBCZYKOWA",
            "LUBELSKA",
            "LUBLEWSKA",
            "LUBOMIRA SZOPIŃSKIEGO",
            "LUBOWIDZKA",
            "LUBUSKA",
            "LUCYNY KRZEMIENIECKIEJ",
            "LUDOMIRA RÓŻYCKIEGO",
            "LUDOWA",
            "LUDWIKA BEETHOVENA",
            "LUDWIKA HIRSZFELDA",
            "LUDWIKA MIEROSŁAWSKIEGO",
            "LUDWIKA PASTEURA",
            "LUDWIKA RYDYGIERA",
            "LUDWIKA SOLSKIEGO",
            "LUDWIKA WARYŃSKIEGO",
            "LUDWIKA ZAMENHOFA",
            "LUTNIOWA",
            "LWOWSKA",
            "BOLESŁAWA KRZYWOUSTEGO",
            "FUNDAMENTOWA",
            "ANTONIEGO SŁONIMSKIEGO",
            "ANTONIEGO SUCHANKA",
            "WACŁAWA BALCERSKIEGO",
            "WACŁAWA KŁOCZKOWSKIEGO",
            "WAJDELOTY",
            "WALECZNYCH",
            "WAŁOWA",
            "WAŁY JAGIELLOŃSKIE",
            "WAŁY PIASTOWSKIE",
            "WARNEŃSKA",
            "WARSZAWSKA",
            "WARTKA",
            "WARZYWNICZA",
            "WAWELSKA",
            "WĄSKOTOROWA",
            "WĄWÓZ",
            "WCZASY",
            "WDZYDZKA",
            "WEGI",
            "WENUS",
            "WESOŁA",
            "WESTY",
            "WĘGLARSKA",
            "WĘGORZOWA",
            "WĘSIERSKA",
            "WIATRACZNA",
            "WICHROWE WZGÓRZE",
            "WIDLIŃSKA",
            "WIDOK",
            "WIECKA",
            "WIELEWSKA",
            "WIELKIE MŁYNY",
            "WIELKOPOLSKA",
            "WIELOPOLE",
            "WIENIECKA",
            "WIERZBOWA",
            "WIESŁAWA",
            "WIEWIÓRCZA",
            "WIEŻYCKA",
            "WIGIERSKA",
            "WIKTORA GOMULICKIEGO",
            "WILEŃSKA",
            "WILGI",
            "WILHELMA STRYJEWSKIEGO",
            "WILKÓW MORSKICH",
            "WILLOWA",
            "WINCENTEGO POLA",
            "WINCENTEGO PSTROWSKIEGO",
            "WINCENTEGO WITOSA",
            "WINNICKA",
            "WINOGRONOWA",
            "WIOLINOWA",
            "WIOSENNA",
            "WIOSŁOWA",
            "WIOSNY LUDÓW",
            "WIŚLNA",
            "WIŚNIOWA",
            "WITA STWOSZA",
            "WITOLDA DOROSZEWSKIEGO",
            "WITOLDA GRABOWSKIEGO",
            "WITOLDA MAŁCUŻYŃSKIEGO",
            "WŁADYSŁAWA BIEGAŃSKIEGO",
            "WŁADYSŁAWA BRONIEWSKIEGO",
            "WŁADYSŁAWA CIESZYŃSKIEGO",
            "WŁADYSŁAWA CZERMIŃSKIEGO",
            "WŁADYSŁAWA IV",
            "WŁADYSŁAWA JAGIEŁŁY",
            "WŁADYSŁAWA ORKANA",
            "WŁADYSŁAWA PNIEWSKIEGO",
            "WŁADYSŁAWA REYMONTA",
            "WŁADYSŁAWA SYROKOMLI",
            "WŁADYSŁAWA SZAFERA",
            "WŁADYSŁAWA ŚWIECHOCKIEGO",
            "WŁADYSŁAWA ŻELEŃSKIEGO",
            "WŁADYSŁAWOWSKA",
            "WŁASNA STRZECHA",
            "WŁÓCZNIKÓW",
            "WODNA",
            "WODNIKA",
            "WODOPÓJ",
            "WOJCIECHA BOGUSŁAWSKIEGO",
            "WOJCIECHA DRZYMAŁY",
            "WOJCIECHA KĘTRZYŃSKIEGO",
            "WOJSKIEGO",
            "WOLARZA",
            "WOLFGANGA MOZARTA",
            "WOLNOŚCI",
            "WOŁKOWYSKA",
            "WOŁYŃSKA",
            "WOSIA BUDZYSZA",
            "WOŹNICY",
            "WROCŁAWSKA",
            "WRONIA",
            "WRÓBLA",
            "WRZESZCZAŃSKA",
            "WRZEŚNIOWA",
            "WRZOSY",
            "WSCHODNIA",
            "WSPÓLNA",
            "WSPÓŁCZESNA",
            "WYDMY",
            "WYGON",
            "WYPOCZYNKOWA",
            "WYZWOLENIA",
            "ALEJA GEN. JÓZEFA HALLERA",
            "ALEKSANDRY GABRYSIAK",
            "ANASTAZEGO WIKA-CZARNOWSKIEGO",
            "ASTRONAUTÓW",
            "ANTONIEGO MADALIŃSKIEGO",
            "BETONIARZY",
            "BĘDOMIŃSKA",
            "ELŻBIETAŃSKA",
            "ASTRONOMÓW",
            "ASTROWA",
            "ATENY",
            "AUGUSTOWSKA",
            "AUGUSTYNA NECLA",
            "AZALIOWA",
            "BIAŁOSTOCKA",
            "BIAŁOWIESKA",
            "BIESZCZADZKA",
            "BIESZKOWICKA",
            "BISKUPIA",
            "BITWY OLIWSKIEJ",
            "BITWY POD LENINO",
            "BIWAKOWA",
            "BLAISE'A PASCALA",
            "BLISKA",
            "BLIŹNIĄT",
            "BLUSZCZOWA",
            "BŁĘKITNA",
            "BŁOŃSKA",
            "BOBROWA",
            "BOCZNA",
            "KACZA",
            "KACZEŃCE",
            "KADETÓW",
            "KADMOWA",
            "KALETNICZA",
            "KALINOWA",
            "KALISKA",
            "KAMIENNA GROBLA",
            "KAMPINOSKA",
            "KANAŁOWA",
            "KAPLICZNA",
            "KAPRÓW",
            "KARKONOSKA",
            "KARLIKOWSKA",
            "KAROLA CHODKIEWICZA",
            "KAROLA DICKENSA",
            "KAROLA KURPIŃSKIEGO",
            "KAROLA LIPIŃSKIEGO",
            "KAROLA OLSZEWSKIEGO",
            "KAROLA SZYMANOWSKIEGO",
            "KARPACKA",
            "KARSIŃSKA",
            "KARTUSKA",
            "KARWIEŃSKA",
            "KASJOPEI",
            "KASZTANOWA",
            "KASZUBSKA",
            "KATARZYNKI",
            "KAZIMIERZA GÓRSKIEGO",
            "KAZIMIERZA JEŻEWSKIEGO",
            "KAZIMIERZA KOPECKIEGO",
            "KAZIMIERZA LESKIEGO",
            "KAZIMIERZA PORĘBSKIEGO",
            "KAZIMIERZA PUŁASKIEGO",
            "KAZIMIERZA SOŚNICKIEGO",
            "KAZIMIERZA TETMAJERA",
            "KAZIMIERZA WIELKIEGO",
            "KAZIMIERZA WIŁKOMIRSKIEGO",
            "KAZNODZIEJSKA",
            "KEMPINGOWA",
            "KĘPNA",
            "KIELECKA",
            "KIELNIEŃSKA",
            "KISZEWSKA",
            "KLIMATYCZNA",
            "KLINICZNA",
            "KLONOWA",
            "KLUKOWSKA",
            "KŁADKI",
            "KŁOPOT",
            "KŁOSOWA",
            "KMIECA",
            "KMINKOWA",
            "KNYSZYŃSKA",
            "KOCURKI",
            "KOLARSKA",
            "KOLBUDZKA",
            "KOLEJARZY",
            "KOLEJOWA",
            "KOLONIA ANIELINKI",
            "KOLONIA JORDANA",
            "KOLONIA MYSIA",
            "KOLONIA OCHOTA",
            "KOLONIA ORKA",
            "KOLONIA POSTĘP",
            "KOLONIA PRACA",
            "KOLONIA PRZYBYSZEWSKIEGO",
            "KOLONIA PRZYSZŁOŚĆ",
            "KOLONIA ROLA",
            "KOLONIA STUDENTÓW",
            "KOLONIA URODA",
            "KOLONIA WYŻYNY",
            "KOLONIA ZARANIE",
            "KOLONIA ZRĘBY",
            "KOLONIJNA",
            "KOLOROWA",
            "KOŁOBRZESKA",
            "KOŁODZIEJSKA",
            "KOMANDORSKA",
            "KOMBATANTÓW",
            "KOMETY",
            "KONKORDII",
            "KONRADA GUDERSKIEGO",
            "11 LISTOPADA",
            "3 BRYGADY SZCZERBCA",
            "3 MAJA",
            "ACHILLESA",
            "ADAMA ASNYKA",
            "ADAMA MICKIEWICZA",
            "ADOLFA DYGASIŃSKIEGO",
            "AFRODYTY",
            "AKACJOWA",
            "AKSAMITNA",
            "AKTEONA",
            "ALDONY",
            "BAJKI",
            "BAŁTYCKA",
            "BANIŃSKA",
            "BARKOCZYŃSKA",
            "BARNIEWICKA",
            "BAROKOWA",
            "BARTKA",
            "BARWNA",
            "BASTION ŚW. ELŻBIETY",
            "BAŚNIOWA",
            "BATALIONÓW CHŁOPSKICH",
            "BATOREGO",
            "BEDNARSKA",
            "BENZYNOWA",
            "FRANCISZKA MAMUSZKI",
            "FRANCISZKA RAKOCZEGO",
            "ŁAGOWSKA",
            "ŁAMANA",
            "ŁAPIŃSKA",
            "ŁAWNICZA",
            "ALEKSANDRA ORŁOWSKIEGO",
            "ALEKSANDRA POTYRAŁY",
            "ANTONIEGO DOBROWOLSKIEGO",
            "ARIADNY",
            "ANTONIEGO ANTCZAKA",
            "BORKOWSKA",
            "CEDROWA",
            "CEFEUSZA",
            "CEGLANA",
            "CEMENTOWA",
            "CENTAURA",
            "CERERY",
            "CHABROWA",
            "CHARZYKOWSKA",
            "CHEŁMIŃSKA",
            "CHIRONA",
            "CHLEBNICKA",
            "CHŁODNA",
            "CHŁOPSKA",
            "CHMIELNA",
            "CHOCZEWSKA",
            "CHOJNICKA",
            "CHRISTIANA ANDERSENA",
            "CHRYZOSTOMA PASKA",
            "CHWASZCZYŃSKA",
            "CIASNA",
            "CICHA",
            "CIECHANOWSKA",
            "CIENISTA",
            "CIETRZEWIA",
            "CISOWA",
            "CMENTARNA",
            "CUMOWNIKÓW",
            "CYGAŃSKA GÓRA",
            "CYPRYSOWA",
            "CYSTERSÓW",
            "CYTROWA",
            "CZAPLEWSKA",
            "CZARNA",
            "CZARNY DWÓR",
            "CZEREMCHOWA",
            "CZEREŚNIOWA",
            "CZERSKA",
            "CZERWCOWA",
            "CZERWONY DWÓR",
            "CZESŁAWA MIŁOSZA",
            "CZĘSTOCHOWSKA",
            "CZŁUCHOWSKA",
            "CZOPOWA",
            "CZYŻYKÓW",
            "RABATKI",
            "RACŁAWICKA",
            "RADAROWA",
            "RADIOWA",
            "RADNA",
            "RADOMSKA",
            "RADOSNA",
            "RADUNICKA",
            "RADUŃSKA",
            "RAJSKA",
            "RAKIETOWA",
            "REDUTA WILK",
            "REDUTA WYSKOK",
            "REDUTA ŻBIK",
            "REFEKTARSKA",
            "REFORMACKA",
            "REGATOWA",
            "REJENTA",
            "REKOWSKA",
            "RELAKSOWA",
            "REMUSA",
            "RENESANSOWA",
            "ROBERTA FULTONA",
            "ROBERTA SCHUMANA",
            "ROBOTNICZA",
            "RODZINNA",
            "ROGALIŃSKA",
            "ROKITNIKOWA",
            "ROLNA",
            "ROMANA DMOWSKIEGO",
            "ROMANA I APOLONII OGRYCZAKÓW",
            "ROMANA WYROBKA",
            "ROMAŃSKA",
            "ROMUALDA TRAUGUTTA",
            "ROSICZKI",
            "ROZŁOGI",
            "RÓWNA",
            "RÓŻANA",
            "RÓŻANY STOK",
            "RÓŻY OSTROWSKIEJ",
            "RUBINOWA",
            "RUFOWA",
            "RUMIANKOWA",
            "RUSAŁKI",
            "RYBACKA",
            "RYBACKIE POBRZEŻE",
            "RYBAKI DOLNE",
            "RYBAKI GÓRNE",
            "RYBITWY",
            "RYBNA",
            "RYBOŁOWCÓW",
            "RYCERZA BLIZBORA",
            "RYSIA",
            "RYSZARDA TOMCZAKA",
            "RYSZARDA WAGNERA",
            "RZECZNA",
            "RZEPICHY",
            "RZEŹNICKA",
            "RZĘSNA",
            "SALWATOR",
            "SAMBORA",
            "SAMUELA LINDEGO",
            "SANDOMIERSKA",
            "SANECZKARSKA",
            "SAPERÓW",
            "SARNIA",
            "SASANKOWA",
            "SATELITARNA",
            "SATURNA",
            "SĄSIEDZKA",
            "SEBASTIANA KLONOWICZA",
            "SECESYJNA",
            "SELENY",
            "SERDECZNA",
            "SEWERYNA GOSZCZYŃSKIEGO",
            "SIANOWSKA",
            "SIELSKA",
            "SIENNA",
            "SIENNICKA",
            "SIERAKOWICKA",
            "SIEROCA",
            "SIERPNIOWA",
            "SIERPOWA",
            "SITOWIE",
            "SKIBY",
            "SKRAJNA",
            "SŁODOWNIKÓW",
            "SŁOMIANA",
            "SŁONACZNA DOLINA",
            "SŁONECZNA",
            "SŁONECZNA DOLINA",
            "ŚCIEŻKI",
            "ŚLĄSKA",
            "ŚLIWKOWA",
            "ŚLUZA",
            "ŚNIADECKICH",
            "ŚNIEŻNA",
            "ŚW. BARBARY",
            "ŚW. BRATA ALBERTA",
            "ŚW. DUCHA",
            "ŚW. HUBERTA",
            "ŚW. TRÓJCY",
            "ŚWIBNIEŃSKA",
            "ŚWIDNICKA",
            "ŚWIECHOCKIEGO",
            "ŚWIERKOWA",
            "ŚWIĘTOJAŃSKA",
            "ŚWIĘTOKRZYSKA",
            "ŚWIĘTOPEŁKA",
            "ŚWISTAKA",
            "ŚWITEZIANKI",
            "ALEJA JANA PAWŁA II",
            "ANNY JAGIELLONKI",
            "BUDZISZÓW",
            "SKARPOWA",
            "SŁONECZNIKOWA",
            "SŁOWIAŃSKA",
            "SŁOWIKÓW",
            "SŁUPSKA",
            "SMĘGORZYŃSKA",
            "SMĘTNA",
            "SMOLEŃSKA",
            "SMOLNA",
            "SMOŁDZIŃSKA",
            "SMUGOWA",
            "SNYCERZY",
            "SOBOLOWA",
            "SOBÓTKI",
            "SOCHACZEWSKA",
            "SOKOLA",
            "SOŁDKA",
            "SOŁECKA",
            "SOMIŃSKA",
            "SOPOCKA",
            "SÓWKI",
            "SPACEROWA",
            "SPADOCHRONIARZY",
            "SPADZISTA",
            "SPICHRZOWA",
            "SPOKOJNA",
            "SPORTOWA",
            "SREBRNA",
            "SREBRNIKI",
            "STAJENNA",
            "STALOWA",
            "STANISŁAWA DĄBKA",
            "STANISŁAWA DUBOIS",
            "STANISŁAWA HEBANOWSKIEGO",
            "STANISŁAWA KONARSKIEGO",
            "STANISŁAWA KUNICKIEGO",
            "STANISŁAWA LEMA",
            "STANISŁAWA MAŁACHOWSKIEGO",
            "STANISŁAWA MONIUSZKI",
            "STANISŁAWA NOAKOWSKIEGO",
            "STANISŁAWA PAWŁOWSKIEGO",
            "STANISŁAWA SKARŻYŃSKIEGO",
            "STANISŁAWA SOŁDKA",
            "STANISŁAWA STASZICA",
            "STANISŁAWA WĄSOWICZA",
            "STANISŁAWA WITKIEWICZA",
            "STANISŁAWA WORCELLA",
            "STANISŁAWA WYSPIAŃSKIEGO",
            "STARA STOCZNIA",
            "STARE DOMKI",
            "STARODWORSKA",
            "STAROGARDZKA",
            "STAROWIEJSKA",
            "STAROWIŚLNA",
            "STARTOWA",
            "STARY RYNEK OLIWSKI",
            "STĄGIEWNA",
            "STECZKA",
            "STEFANA BATOREGO",
            "STEFANA CZARNIECKIEGO",
            "STEFANA DRZEWIECKIEGO",
            "STEFANA JARACZA",
            "STEFANA KISIELEWSKIEGO",
            "STEFANA MIRAUA",
            "STEFANA OKRZEI",
            "STEFANA RAMUŁTA",
            "STEFANA ŻEROMSKIEGO",
            "STEFANII SEMPOŁOWSKIEJ",
            "STERNICZA",
            "STĘPKARSKA",
            "STĘŻYCKA",
            "STOCZNIOWCÓW",
            "STOKŁOSY",
            "STOKROTKI",
            "STOLARSKA",
            "STOLEMA",
            "STOLNIKA",
            "STORCZYKOWA",
            "STRAGANIARSKA",
            "STRAJKU DOKERÓW",
            "STRASZYŃSKA",
            "STROMA",
            "STRZELCA",
            "STRZELCÓW KARPACKICH",
            "STRZELECKA",
            "SUBISŁAWA",
            "SUCHA",
            "SUDOMSKA",
            "SUKIENNICZA",
            "SULMIŃSKA",
            "SUWALSKA",
            "SWARZEWSKA",
            "SWOJSKA",
            "SYMPATYCZNA",
            "SYNÓW PUŁKU",
            "SYRIUSZA",
            "SZAFARNIA",
            "SZAFIROWA",
            "SZAFRANOWA",
            "SZALUPOWA",
            "SZARA",
            "SZAROTKI",
            "SZCZECIŃSKA",
            "SZCZECIŃŚKA",
            "SZCZEPANA PILECKIEGO",
            "SZCZĘŚLIWA",
            "SZCZODRA",
            "SZCZYTNIKÓW",
            "SZERMIERCZA",
            "SZEROKA",
            "SZEWSKA",
            "SZKLANA HUTA",
            "SZKOCKA",
            "SZKUTNICZA",
            "SZMARAGDOWA",
            "SZOPY",
            "SZPAKI",
            "SZPITALNA",
            "SZTORMOWA",
            "SZTUTOWSKA",
            "SZUWARY",
            "SZYBOWCOWA",
            "SZYMBARSKA",
            "SZYNSZYLOWA",
            "SZYPRÓW",
            "ŁOZY",
            "ALEJA RZECZYPOSPOLITEJ"
    };

    public List<String> getStreets(){
        return Arrays.asList(streets);
    }
}
